name: fsfdsfa
description: ihi
version: a
author: kiran@prophecy.io
language: python
buildSystem: wheel
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: kiran@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-07-14 11:43:09'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
dependencies: '[]'
